// Los textos del portal del vecino, en todos los idiomas.
//
//   const { textos } = require('./idiomas');
//   const t = textos(v.idioma);
//   t('perfil.titulo')   // "Mi Perfil" / "My Profile" / "Meu Perfil" / "Mon Profil"
//
// POR QUÉ EXISTE. Un huésped que llega de Brasil o de Estados Unidos abre el portal para abrirle
// la puerta a alguien o para reservar la parrilla. Si no entiende lo que dice la pantalla, no es
// que "le cuesta": no puede usarlo, y el propietario termina haciéndole todo por teléfono — que es
// exactamente el trabajo que este sistema viene a sacarse de encima.
//
// CÓMO AGREGAR UN IDIOMA. Se copia el bloque `es` entero, se traduce, y se agrega a `IDIOMAS`.
// Nada más: no hay que tocar ninguna pantalla. `pruebas-idiomas.js` exige que el idioma nuevo
// tenga TODAS las claves, así que una traducción a medias no llega a producción.
//
// > [!CAUTION]
// > **Una clave que falta NO puede renderizar vacío.** Un cartel en blanco en el medio de una
// > pantalla es el peor error posible acá: nadie sabe qué decía, y el que lo sufre es justamente
// > el que no puede leer el resto para deducirlo. Por eso `t()` cae al castellano cuando falta,
// > y la prueba rompe antes de que eso llegue a pasar.

const IDIOMAS = [
    { codigo: 'es', nombre: 'Español',    bandera: '🇦🇷' },
    { codigo: 'en', nombre: 'English',    bandera: '🇺🇸' },
    { codigo: 'pt', nombre: 'Português',  bandera: '🇧🇷' },
    { codigo: 'fr', nombre: 'Français',   bandera: '🇫🇷' },
];

const IDIOMA_POR_DEFECTO = 'es';

const TEXTOS = {
    es: {
        'nav.inicio': 'Inicio',
        'nav.chat': 'Marcos IA',
        'nav.porteria': 'Portería',
        'nav.amenities': 'Amenities',
        'nav.expensas': 'Expensas',
        'nav.avisos': 'Avisos',

        'topbar.hola': 'Hola, {nombre}',
        'topbar.perfil': 'Mi Perfil',
        'topbar.tema': 'Cambiar tema',
        'topbar.salir': 'Cerrar sesión',
        'topbar.idioma': 'Idioma',

        'rol.propietario': 'Propietario',
        'rol.inquilino': 'Inquilino',
        'rol.turista': 'Huésped',
        'rol.asistente': 'Gestor',
        'rol.registrado': 'Sin unidad',

        'perfil.titulo': 'Mi Perfil',
        'perfil.bajada': 'Tus datos, tus unidades y tu acceso',
        'perfil.datos': 'Mis datos',
        'perfil.nombre': 'Nombre',
        'perfil.apellido': 'Apellido',
        'perfil.telefono': 'Teléfono de contacto',
        'perfil.email': 'Email registrado',
        'perfil.emailNota': 'El email es con el que el titular te vincula a la unidad. Para cambiarlo, escribinos por Marcos IA.',
        'perfil.guardar': 'Guardar cambios',
        'perfil.guardado': 'Datos guardados.',
        'perfil.sinNombre': 'El nombre no puede quedar vacío',
        'perfil.idioma': 'Idioma de la aplicación',
        'perfil.idiomaNota': 'Cambia lo que ves en pantalla. Podés cambiarlo cuando quieras.',
        'perfil.unidades': 'Mis unidades',
        'perfil.unidadesNota': 'Elegí cuál estás mirando. Expensas, reclamos y amenities siguen a la unidad activa.',
        'perfil.viendo': 'Viendo',
        'perfil.usarEsta': 'Usar esta',
        'perfil.sinExpensas': 'sin expensas',
        'perfil.sinUnidades': 'Todavía no tenés ninguna unidad vinculada. Pedile al titular del departamento (o a la administración) que te habilite con tu email {email} desde la pestaña Integrantes.',
        'perfil.estadia': 'Tu estadía',
        'perfil.desde': 'Desde',
        'perfil.hasta': 'Hasta',
        'perfil.pase': 'Pase QR temporal',
        'perfil.paseVence': 'Vence el {fecha} · mostralo en el tótem de la entrada',
        'perfil.acceso': 'Acceso y seguridad',
        'perfil.accesoNota': 'También podés entrar con un código que te llega por WhatsApp, sin contraseña.',
        'perfil.passActual': 'Contraseña actual',
        'perfil.passActualPlaceholder': 'Dejala vacía si nunca pusiste una',
        'perfil.passNueva': 'Contraseña nueva',
        'perfil.passNuevaPlaceholder': 'Mínimo 6 caracteres',
        'perfil.passRepetir': 'Repetir la nueva',
        'perfil.passRepetirPlaceholder': 'Igual que la anterior',
        'perfil.cambiarPass': 'Cambiar contraseña',
        'perfil.passCambiada': 'Contraseña actualizada.',
        'perfil.passDistintas': 'Las dos contraseñas nuevas no son iguales.',
        'perfil.salir': 'Cerrar sesión',
        'perfil.demo': 'Estás en la sesión de prueba. Los cambios de datos y de contraseña no se guardan hasta que entres con tu cuenta.',
        'perfil.sinCuenta': 'Entrá con tu cuenta para cambiar la contraseña',

        'inicio.expensasTab': 'Expensas (Ord. y Extraord.)',
        'inicio.reservasTab': 'Reservas',
        'inicio.reclamosTab': 'Reclamos',
        'inicio.totalAPagar': 'Total a Pagar (Mes Vigente)',
        'inicio.vencimiento': 'Vencimiento: 10 del mes · Ordinarias y Extraordinarias',
        'inicio.pagarExpensa': 'Pagar Expensa',
        'inicio.verRecibo': 'Ver Recibo PDF',
        'inicio.timbre': 'Mi Timbre Digital',
        'inicio.timbreActivo': 'Activo · Suena en tu celu',
        'inicio.timbreInactivo': 'Apagado',
        'inicio.noMolestar': 'Modo "No Molestar"',
        'inicio.horarioSilencio': 'Horario de silencio:',
        'inicio.timbreGuardado': 'Preferencia de timbre guardada',
        'inicio.accesosDirectos': 'Accesos Directos',
        'inicio.pasesQr': 'Pases QR',
        'inicio.porteriaQr': 'Portería QR',
        'inicio.amenities': 'Amenities',
        'inicio.integrantes': 'Integrantes',
        'inicio.instalarTitulo': 'Instalar App en tu Celular',
        'inicio.instalarBajada': 'Acceso rápido directo en tu pantalla',
        'inicio.instalar': 'Instalar',
        'inicio.asistenteTitulo': 'Asistente Consorcio 24/7',
        'inicio.asistenteBajada': 'Reportá una urgencia, consultá expensas o el reglamento.',
        'inicio.chatear': 'Chatear',
        'inicio.servicios': 'Servicios',
        'inicio.ascensor': 'Ascensor Principal',
        'inicio.ascensorEstado': 'En servicio normal',
        'inicio.bombas': 'Bombas de Agua',
        'inicio.bombasEstado': 'Presión estándar',
        'inicio.porton': 'Portón Cochera',
        'inicio.portonEstado': 'Apertura automática',
        'inicio.novedades': 'Novedades del Consorcio',
        'inicio.verTodas': 'Ver todas',
        'inicio.mantenimiento': 'Mantenimiento',
        'inicio.avisoTanques': 'Limpieza programada de tanques',
        'inicio.avisoTanquesTexto': 'Se realizará el jueves de 08:00 a 14:00 hs. Habrá baja presión momentánea.',
        'inicio.estadiaTemporal': 'Estadía Temporal',
        'inicio.paseHuesped': 'Pase Huésped Activo',
        'inicio.alojadoEn': 'Alojado en depto',
        'inicio.huespedBienvenida': 'Tenés acceso habilitado a reservas de amenities, timbre personal y Marcos IA 24/7.',
        'inicio.cuentaCreada': 'Cuenta Creada',
        'inicio.sinDepto': 'Todavía no tenés ningún departamento asignado.',
        'inicio.comoSigo': '¿Cómo continúo?',
        'inicio.comoSigoTexto': 'Enviá un mensaje con el email con el que te registraste ({email}) a la persona que te invitó (propietario, anfitrión o administración) para que te habilite el acceso a la unidad.',
        'inicio.asistencia24': 'Asistencia 24hs',

        'avisos.titulo': 'Avisos de {edificio}',
        'avisos.hasta': 'hasta el {fecha}',
        'avisos.sinFecha': 'hasta nuevo aviso',
        'avisos.publicadoPor': 'Avisó {quien} ({rol})',
        'avisos.reclamoAbierto': 'Reclamo abierto, todavía sin resolver',

        'expensa.sinCargar': 'La expensa de este mes todavía no está cargada.',
        'expensa.vence': 'Vence el {fecha}',
        'expensa.descargar': 'Descargar',
        'expensa.delEdificio': 'Es la expensa general del edificio, no la de tu unidad.',
        'expensa.liquidacionEdificio': 'Liquidación del edificio',

        // ── PASES QR ──
        'pases.titulo': 'Pases de invitación QR',
        'pases.nuevo': 'Nuevo pase QR',
        'pases.tabActivos': 'Pases activos',
        'pases.tabHistorial': 'Historial / vencidos',
        'pases.crearTitulo': 'Crear pase de invitación QR',
        'pases.nombreInvitado': 'Nombre del invitado o proveedor',
        'pases.nombrePlaceholder': 'Ej: Lucas González, o el cadete del delivery',
        'pases.motivo': 'Motivo de la visita',
        'pases.motivoDelivery': 'Delivery',
        'pases.motivoVisita': 'Visita',
        'pases.motivoEncomienda': 'Encomienda',
        'pases.motivoProveedor': 'Proveedor',
        'pases.validez': 'Validez del pase',
        'pases.validez2h': '2 horas (para un delivery)',
        'pases.validez4h': '4 horas (para una visita)',
        'pases.validezDia': 'Todo el día (hasta las 23:59)',
        'pases.validezCustom': 'Fecha y hora que elijas',
        'pases.desde': 'Desde',
        'pases.hasta': 'Hasta',
        'pases.recurrente': 'Que se repita (servicio de limpieza, por ejemplo)',
        'pases.diasHabilitados': 'Días de la semana',
        'pases.horaEntrada': 'Hora de entrada',
        'pases.horaSalida': 'Hora de salida',
        'pases.generar': 'Generar pase y ver el código QR',
        'pases.generando': 'Generando el pase…',
        'pases.habilitado': 'Pase habilitado',
        'pases.invitado': 'Invitado',
        'pases.compartirWhatsapp': 'Compartir por WhatsApp',
        'pases.copiarEnlace': 'Copiar el enlace del pase',
        'pases.sinActivos': 'No tenés ningún pase activo en este momento.',
        'pases.activo': 'Activo',
        'pases.codigo': 'Código',
        'pases.vence': 'Vence',
        'pases.verQr': 'Ver el QR / enviar',
        'pases.sinHistorial': 'Todavía no hay pases anteriores.',
        'pases.validoHasta': 'Válido hasta',
        'pases.estadoUtilizado': 'Usado',
        'pases.estadoRevocado': 'Anulado',
        'pases.estadoVencido': 'Vencido',
        'dia.lun': 'Lun',
        'dia.mar': 'Mar',
        'dia.mie': 'Mié',
        'dia.jue': 'Jue',
        'dia.vie': 'Vie',
        'dia.sab': 'Sáb',
        'dia.dom': 'Dom',

        // ── EXPENSAS ──
        'exp.titulo': 'Mis expensas',
        'exp.liquidacionMes': 'Liquidación del mes',
        'exp.digital': 'Digital',
        'exp.periodoVigente': 'Período vigente',
        'exp.periodoEnProceso': 'Todavía sin período',
        'exp.totalAPagar': 'Total a pagar',
        'exp.venceEl': 'Vence el {fecha}',
        'exp.publicadoSinTotal': 'La administración publicó el documento de este período. El total todavía no está cargado.',
        'exp.aunNoPublicada': 'La administración va a publicar la liquidación de este mes en los próximos días.',
        'exp.verDescargar': 'Ver o descargar la liquidación',
        'exp.pedirPorChat': 'Le podés pedir una copia a Marcos por el chat, cuando quieras.',
        'exp.datosTransferencia': 'Para transferir',
        'exp.cuentaOficial': 'Cuenta del consorcio',
        'exp.titular': 'Titular',
        'exp.banco': 'Banco',
        'exp.alias': 'Alias',
        'exp.copiar': 'Copiar',
        'exp.sinDatosBanco': 'Todavía no están cargados los datos de la cuenta',
        'exp.sinDatosBancoAyuda': 'Pedíselos a la Administración antes de transferir. No los inventamos: una transferencia a una cuenta equivocada no se puede deshacer.',
        'exp.informarPago': 'Informar el pago de las expensas',
        'exp.informarAyuda': 'Adjuntá el comprobante de la transferencia',
        'exp.comprobante': 'Comprobante de la transferencia (foto o PDF)',
        'exp.elegirAyuda': 'Tocá para elegirlo de tu teléfono o de la galería',
        'exp.importe': 'Importe que transferiste',
        'exp.importePlaceholder': 'Ej: 85400',
        'exp.enviar': 'Enviar el comprobante',
        'exp.enviando': 'Enviando el comprobante…',
        'exp.faltaComprobante': 'Primero adjuntá el comprobante',
        'exp.misComprobantes': 'Los comprobantes que mandé',
        'exp.misComprobantesAyuda': 'En qué quedó cada transferencia',
        'exp.imputado': 'Imputado',
        'exp.enRevision': 'En revisión',
        'exp.comprobante1': 'Comprobante',
        'exp.informado': 'Informado',
        'exp.reciente': 'Reciente',
        'exp.historial': 'Liquidaciones anteriores',
        'exp.historialAyuda': 'Podés descargar cualquiera',
        'exp.periodo': 'Período',
        'exp.liquidacion': 'Liquidación de expensas',
        'exp.descargarPdf': 'Descargar',
        'exp.copiado': 'Copiado',
        'exp.delEdificioNota': 'Es la liquidación general del edificio, no la de tu unidad. El detalle está en el documento.',
        // ── INTEGRANTES DE LA UNIDAD ──
        'int.volver': 'Volver al inicio',
        'int.asignarTitulo': 'Sumar a alguien a la unidad',
        'int.asignarAyuda': 'Convivientes, inquilinos, huéspedes o quien te administra la propiedad',
        'int.paso1': '1. Qué es esa persona en el departamento',
        'int.rolFamiliar': 'Familiar o conviviente',
        'int.rolInquilino': 'Inquilino',
        'int.rolTurista': 'Huésped por unos días',
        'int.rolAsistente': 'Quien me administra la propiedad',
        'int.paso2': '2. Email con el que se registró',
        'int.verificando': 'Buscando…',
        'int.emailPlaceholder': 'ejemplo: usuario@correo.com',
        'int.fechasEstadia': 'Fechas de la estadía',
        'int.checkin': 'Llega',
        'int.checkout': 'Se va',
        'int.turistaSinExpensas': 'El huésped no ve las expensas. Solo el timbre, las reservas y el chat con Marcos.',
        'int.cesionGestion': 'Cesión de gestión:',
        'int.cesionAyuda': 'La unidad pasa a la cartera de quien la administra. Va a poder coordinar estadías, registrar huéspedes, pedir reubicaciones y abrir reclamos en tu nombre.',
        'int.activosTitulo': 'Quién tiene acceso',
        'int.activosAyuda': 'Personas con acceso a la unidad',
        'int.cargando': 'Cargando…',
        'int.reubicarTitulo': 'Mudar a un huésped a otra unidad',
        'int.huespedATrasladar': 'Huésped que se muda',
        'int.cargandoHuespedes': 'Cargando huéspedes…',
        'int.unidadDestino': 'A qué unidad va',
        'int.cargandoUnidades': 'Cargando unidades…',
        'int.motivoTraslado': 'Por qué se muda',
        'int.motivoPlaceholder': 'Ej: pierde agua, o una reparación urgente',
        'int.efectos': 'Lo que pasa al confirmar:',
        'int.confirmarReubicacion': 'Confirmar la mudanza',
        'int.reubicando': 'Mudando…',
        'int.guardando': 'Guardando…',
        'int.usuarioVerificado': 'Encontramos a esta persona en la app',
        'int.usuarioNoRegistrado': 'No encontramos a nadie con ese email',
        'int.usuarioNoRegistradoAyuda': 'La persona tiene que registrarse primero en la app con su email y su teléfono. Después la podés sumar a la unidad.',
        'int.faltaUsuario': 'Primero tenés que poner el email de alguien registrado en la app.',
        'int.asignado': 'Listo, ya tiene acceso a la unidad.',
        'int.errorAsignar': 'No se pudo sumar a esa persona.',
        'int.confirmarDesvincular': '¿Seguro que querés sacarle el acceso a {nombre}?',
        'int.desvinculado': 'Listo, ya no tiene acceso.',
        'int.errorConexion': 'No se pudo conectar. Probá de nuevo.',
        'int.elegirHuesped': 'Elegir huésped…',
        'int.elegirDestino': 'Elegir la unidad de destino…',
        'int.errorPortafolio': 'No se pudo consultar la cartera',
        'int.faltaHuespedDestino': 'Elegí el huésped y la unidad de destino.',
        'int.reubicado': 'Listo, el huésped ya está en la otra unidad.',
        'int.errorReubicar': 'No se pudo mudar al huésped.',
        'int.badgeTurista': 'Huésped',
        'int.badgePropietario': 'Propietario',
        'int.badgeAsistente': 'Administra la propiedad',
        'int.badgeInquilino': 'Inquilino',
        'int.badgeFamiliar': 'Familiar',
        'int.timbreOn': 'Timbre activado',
        'int.timbreOff': 'Timbre apagado',
        'int.reubicarDepto': 'Mudar de unidad',
        'int.desvincular': 'Sacar acceso',
        'int.huesped': 'Huésped',
        'int.dueno': 'Dueño',
        'int.del': 'Del',
        'int.al': 'al',
        // ── AVISOS DEL EDIFICIO Y CHAT ──
        'nov.titulo': 'Avisos del edificio',
        'nov.subtitulo': 'Lo que la administración comunicó en {edificio}',
        'nov.sinAvisos': 'No hay avisos',
        'nov.sinAvisosAyuda': 'Cuando haya un corte de agua, una fumigación o algo fuera de lo común, lo vas a ver acá.',
        'chat.enLinea': 'Marcos en línea',
        'chat.atencion': 'Te contestamos a cualquier hora',
        'chat.whatsapp': 'WhatsApp',
        'chat.saludo': '¡Hola {nombre}! Soy Marcos, el asistente de {edificio}. ¿En qué te puedo ayudar? Podés preguntarme por las expensas, avisar de algo roto, o pedirme datos del edificio.',
        'chat.sug1': '¿Cuándo vencen las expensas?',
        'chat.sug2': 'Pierde agua en el baño',
        'chat.sug3': 'Horario y reglamento del SUM',
        'chat.adjuntar': 'Podés adjuntar fotos de algo roto o un comprobante',
        'chat.placeholder': 'Escribile a Marcos…',
        'chat.recibido': 'Listo, lo tomé. Cualquier novedad te aviso.',
        'chat.recibidoCorto': 'Listo, recibí tu mensaje.',
        // ── RECLAMOS Y AVERÍAS ──
        'recl.titulo': 'Reclamos y averías',
        'recl.reportar': 'Reportar una rotura',
        'recl.enGestion': 'En gestión',
        'recl.resueltos': 'Resueltos',
        'recl.misCasos': 'Mis casos',
        'recl.misReportados': 'Lo que reporté',
        'recl.sinActivos': 'No tenés reclamos activos',
        'recl.sinActivosAyuda': 'Si ves algo roto en tu departamento o en el edificio, lo podés reportar acá.',
        'recl.areasComunes': 'Averías en áreas comunes',
        'recl.modalTitulo': 'Reportar un reclamo o una rotura',
        'recl.rubro': 'Tipo de problema',
        'recl.rubroPlomeria': 'Plomería',
        'recl.rubroElectricidad': 'Electricidad',
        'recl.rubroAscensor': 'Ascensor',
        'recl.rubroPorton': 'Portón / acceso',
        'recl.rubroGas': 'Gas',
        'recl.rubroLimpieza': 'Limpieza',
        'recl.ubicacion': 'Dónde está el problema',
        'recl.enMiDepto': 'En mi departamento ({depto})',
        'recl.areaComun': 'En un área común',
        'recl.descripcion': 'Contá qué pasa',
        'recl.descPlaceholder': 'Contá con detalle qué pasa. Por ejemplo: pierde agua abajo de la pileta, o no prende la luz del pasillo.',
        'recl.foto': 'Foto de la rotura (ayuda mucho)',
        'recl.fotoBoton': 'Sacar una foto o elegir una de la galería',
        'recl.fotoAyuda': 'Con la foto, el técnico puede traer el repuesto que hace falta',
        'recl.urgencia': 'Marcar como urgencia grave',
        'recl.urgenciaAyuda': 'Inundación, corte de luz general, olor a gas o riesgo para alguien',
        'recl.enviar': 'Enviar el reclamo',
        'recl.enviando': 'Registrando el reclamo…',
        'recl.errorEnviar': 'No se pudo registrar el reclamo',
        'recl.estadoResuelto': 'Resuelto',
        'recl.estadoEnCurso': 'En curso',
        'recl.estadoPendiente': 'Pendiente',
        'recl.averia': 'Avería',
        'recl.reciente': 'Recién',
        'recl.ampliar': 'Tocá para ampliar',
        // ── ESPACIOS COMUNES (AMENITIES) ──
        'amen.titulo': 'Reserva de espacios comunes',
        'amen.subtitulo': 'Espacios comunes y turnos por hora en {edificio}',
        'amen.misReservas': 'Mis reservas',
        'amen.nueva': 'Nueva reserva por horas',
        'amen.paso1': '1. Elegí el espacio',
        'amen.paso2': '2. Elegí la fecha',
        'amen.paso3': '3. Tocá las horas que vas a usar (bloques de 1 hora)',
        'amen.libreOcupado': '🟩 Libre · 🟥 Ocupado',
        'amen.motivoOpcional': 'Motivo o cantidad de personas (opcional)',
        'amen.motivoPlaceholder': 'Ej: cumpleaños familiar, o reunión de trabajo',
        'amen.confirmar': 'Confirmar la reserva',
        'amen.reglamento': 'Reglamento',
        'amen.sinCosto': 'Sin costo',
        'amen.sinCostoEspacio': 'Este espacio no tiene costo',
        'amen.fijo': 'fijo',
        'amen.pagoAprobado': 'Pago aprobado',
        'amen.pagoEnRevision': 'Pago en revisión',
        'amen.comprobanteObservado': 'Comprobante observado',
        'amen.pagoPendiente': 'Pago pendiente',
        'amen.verComprobante': 'Ver el comprobante',
        'amen.subirNuevo': 'Subir otro comprobante',
        'amen.subirComprobante': 'Subir el comprobante',
        'amen.observacionAdmin': 'Observación de la administración:',
        'amen.observacionDefault': 'El comprobante anterior no se pudo verificar. Por favor adjuntá uno nuevo que se lea bien.',
        'amen.cancelar': 'Cancelar',
        'amen.informarPago': 'Informar el pago de la reserva',
        'amen.espacioAAbonar': 'Espacio a abonar:',
        'amen.datosBancarios': 'Datos bancarios del consorcio',
        'amen.titular': 'Titular',
        'amen.alias': 'Alias',
        'amen.copiar': 'Copiar',
        'amen.adjuntar': 'Adjuntar el comprobante (foto o PDF)',
        'amen.elegirArchivo': 'Elegir la foto o el PDF del comprobante',
        'amen.elegirAyuda': 'Tocá para elegirlo de tu teléfono o de la galería',
        'amen.montoAbonado': 'Monto que pagaste',
        'amen.montoPlaceholder': 'Ej: 15000',
        'amen.enviarComprobante': 'Enviar el comprobante',
        'amen.arancel': 'Arancel',
        'amen.tarifaFija': 'tarifa fija por reserva',
        'amen.porHora': 'por hora reservada',
        'amen.notaFija': 'El arancel es el mismo, sin importar cuántas horas elijas.',
        'amen.notaPorHora': 'El total se calcula solo: el arancel por la cantidad de horas que elijas.',
        'amen.notaTransferir': 'Cuando confirmes la reserva vas a poder transferir a la cuenta del consorcio y adjuntar el comprobante desde “Mis reservas”.',
        'amen.elegiFecha': 'Elegí una fecha para ver los horarios libres.',
        'amen.totalAAbonar': 'Total a abonar',
        'amen.hora': 'hora',
        'amen.horas': 'horas',
        'amen.reservaHecha': '✓ ¡Reserva tomada, de {desde} a {hasta}!',

        'error.generico': 'No se pudo completar la acción.',
    },

    en: {
        'nav.inicio': 'Home',
        'nav.chat': 'Marcos AI',
        'nav.porteria': 'Entrance',
        'nav.amenities': 'Amenities',
        'nav.expensas': 'Fees',
        'nav.avisos': 'Notices',

        'topbar.hola': 'Hi, {nombre}',
        'topbar.perfil': 'My Profile',
        'topbar.tema': 'Switch theme',
        'topbar.salir': 'Sign out',
        'topbar.idioma': 'Language',

        'rol.propietario': 'Owner',
        'rol.inquilino': 'Tenant',
        'rol.turista': 'Guest',
        'rol.asistente': 'Manager',
        'rol.registrado': 'No unit',

        'perfil.titulo': 'My Profile',
        'perfil.bajada': 'Your details, your units and your access',
        'perfil.datos': 'My details',
        'perfil.nombre': 'First name',
        'perfil.apellido': 'Last name',
        'perfil.telefono': 'Contact phone',
        'perfil.email': 'Registered email',
        'perfil.emailNota': 'Your email is what the owner uses to link you to the unit. To change it, message us through Marcos AI.',
        'perfil.guardar': 'Save changes',
        'perfil.guardado': 'Details saved.',
        'perfil.sinNombre': 'Name cannot be empty',
        'perfil.idioma': 'App language',
        'perfil.idiomaNota': 'Changes what you see on screen. You can change it any time.',
        'perfil.unidades': 'My units',
        'perfil.unidadesNota': 'Pick the one you are viewing. Fees, requests and amenities follow the active unit.',
        'perfil.viendo': 'Viewing',
        'perfil.usarEsta': 'Use this one',
        'perfil.sinExpensas': 'no fees',
        'perfil.sinUnidades': 'You have no unit linked yet. Ask the apartment owner (or the building manager) to add you with your email {email} from the Members tab.',
        'perfil.estadia': 'Your stay',
        'perfil.desde': 'From',
        'perfil.hasta': 'To',
        'perfil.pase': 'Temporary QR pass',
        'perfil.paseVence': 'Expires on {fecha} · show it at the entrance kiosk',
        'perfil.acceso': 'Access and security',
        'perfil.accesoNota': 'You can also sign in with a code sent to you on WhatsApp, without a password.',
        'perfil.passActual': 'Current password',
        'perfil.passActualPlaceholder': 'Leave empty if you never set one',
        'perfil.passNueva': 'New password',
        'perfil.passNuevaPlaceholder': 'At least 6 characters',
        'perfil.passRepetir': 'Repeat the new one',
        'perfil.passRepetirPlaceholder': 'Same as above',
        'perfil.cambiarPass': 'Change password',
        'perfil.passCambiada': 'Password updated.',
        'perfil.passDistintas': 'The two new passwords do not match.',
        'perfil.salir': 'Sign out',
        'perfil.demo': 'You are in the demo session. Changes to your details and password are not saved until you sign in with your account.',
        'perfil.sinCuenta': 'Sign in with your account to change the password',

        'inicio.expensasTab': 'Fees (regular & special)',
        'inicio.reservasTab': 'Bookings',
        'inicio.reclamosTab': 'Requests',
        'inicio.totalAPagar': 'Total due (current month)',
        'inicio.vencimiento': 'Due: 10th of the month · regular and special',
        'inicio.pagarExpensa': 'Pay now',
        'inicio.verRecibo': 'View PDF receipt',
        'inicio.timbre': 'My digital doorbell',
        'inicio.timbreActivo': 'On · rings on your phone',
        'inicio.timbreInactivo': 'Off',
        'inicio.noMolestar': 'Do not disturb',
        'inicio.horarioSilencio': 'Quiet hours:',
        'inicio.timbreGuardado': 'Doorbell preference saved',
        'inicio.accesosDirectos': 'Shortcuts',
        'inicio.pasesQr': 'QR passes',
        'inicio.porteriaQr': 'QR entrance',
        'inicio.amenities': 'Amenities',
        'inicio.integrantes': 'Members',
        'inicio.instalarTitulo': 'Install the app on your phone',
        'inicio.instalarBajada': 'Quick access right on your home screen',
        'inicio.instalar': 'Install',
        'inicio.asistenteTitulo': '24/7 building assistant',
        'inicio.asistenteBajada': 'Report an emergency, check fees or the rules.',
        'inicio.chatear': 'Chat',
        'inicio.servicios': 'Building services',
        'inicio.ascensor': 'Main lift',
        'inicio.ascensorEstado': 'Running normally',
        'inicio.bombas': 'Water pumps',
        'inicio.bombasEstado': 'Normal pressure',
        'inicio.porton': 'Garage gate',
        'inicio.portonEstado': 'Opens automatically',
        'inicio.novedades': 'Building news',
        'inicio.verTodas': 'See all',
        'inicio.mantenimiento': 'Maintenance',
        'inicio.avisoTanques': 'Scheduled water tank cleaning',
        'inicio.avisoTanquesTexto': 'Thursday from 08:00 to 14:00. Expect low pressure for a while.',
        'inicio.estadiaTemporal': 'Temporary stay',
        'inicio.paseHuesped': 'Guest pass active',
        'inicio.alojadoEn': 'Staying in unit',
        'inicio.huespedBienvenida': 'You have access to amenity bookings, your own doorbell and Marcos AI 24/7.',
        'inicio.cuentaCreada': 'Account created',
        'inicio.sinDepto': 'You have no unit assigned yet.',
        'inicio.comoSigo': 'What now?',
        'inicio.comoSigoTexto': 'Send the email you signed up with ({email}) to whoever invited you — the owner, host or building manager — so they can give you access to the unit.',
        'inicio.asistencia24': '24/7 support',

        'avisos.titulo': 'Notices for {edificio}',
        'avisos.hasta': 'until {fecha}',
        'avisos.sinFecha': 'until further notice',
        'avisos.publicadoPor': 'Posted by {quien} ({rol})',
        'avisos.reclamoAbierto': 'Open request, not resolved yet',

        'expensa.sinCargar': "This month's fee hasn't been uploaded yet.",
        'expensa.vence': 'Due {fecha}',
        'expensa.descargar': 'Download',
        'expensa.delEdificio': "This is the building's general fee, not your unit's.",
        'expensa.liquidacionEdificio': "Building's statement",

        // ── PASES QR ──
        'pases.titulo': 'QR guest passes',
        'pases.nuevo': 'New QR pass',
        'pases.tabActivos': 'Active passes',
        'pases.tabHistorial': 'History / expired',
        'pases.crearTitulo': 'Create a QR guest pass',
        'pases.nombreInvitado': 'Guest or contractor name',
        'pases.nombrePlaceholder': 'e.g. Lucas González, or the delivery rider',
        'pases.motivo': 'Reason for the visit',
        'pases.motivoDelivery': 'Delivery',
        'pases.motivoVisita': 'Visit',
        'pases.motivoEncomienda': 'Parcel',
        'pases.motivoProveedor': 'Contractor',
        'pases.validez': 'How long it lasts',
        'pases.validez2h': '2 hours (for a delivery)',
        'pases.validez4h': '4 hours (for a visit)',
        'pases.validezDia': 'All day (until 11:59 pm)',
        'pases.validezCustom': 'A date and time you choose',
        'pases.desde': 'From',
        'pases.hasta': 'Until',
        'pases.recurrente': 'Make it repeat (a cleaner, for example)',
        'pases.diasHabilitados': 'Days of the week',
        'pases.horaEntrada': 'Arrival time',
        'pases.horaSalida': 'Departure time',
        'pases.generar': 'Create the pass and show the QR code',
        'pases.generando': 'Creating the pass…',
        'pases.habilitado': 'Pass enabled',
        'pases.invitado': 'Guest',
        'pases.compartirWhatsapp': 'Share on WhatsApp',
        'pases.copiarEnlace': 'Copy the pass link',
        'pases.sinActivos': 'You have no active passes right now.',
        'pases.activo': 'Active',
        'pases.codigo': 'Code',
        'pases.vence': 'Expires',
        'pases.verQr': 'Show the QR / send',
        'pases.sinHistorial': 'No earlier passes yet.',
        'pases.validoHasta': 'Valid until',
        'pases.estadoUtilizado': 'Used',
        'pases.estadoRevocado': 'Cancelled',
        'pases.estadoVencido': 'Expired',
        'dia.lun': 'Mon',
        'dia.mar': 'Tue',
        'dia.mie': 'Wed',
        'dia.jue': 'Thu',
        'dia.vie': 'Fri',
        'dia.sab': 'Sat',
        'dia.dom': 'Sun',

        // ── EXPENSAS ──
        'exp.titulo': 'My fees',
        'exp.liquidacionMes': "This month's statement",
        'exp.digital': 'Digital',
        'exp.periodoVigente': 'Current period',
        'exp.periodoEnProceso': 'No period yet',
        'exp.totalAPagar': 'Total to pay',
        'exp.venceEl': 'Due {fecha}',
        'exp.publicadoSinTotal': "The management published this period's document. The total isn't loaded yet.",
        'exp.aunNoPublicada': "The management will publish this month's statement in the next few days.",
        'exp.verDescargar': 'View or download the statement',
        'exp.pedirPorChat': 'You can ask Marcos for a copy in the chat whenever you like.',
        'exp.datosTransferencia': 'To transfer',
        'exp.cuentaOficial': "The building's account",
        'exp.titular': 'Account holder',
        'exp.banco': 'Bank',
        'exp.alias': 'Alias',
        'exp.copiar': 'Copy',
        'exp.sinDatosBanco': "The account details aren't loaded yet",
        'exp.sinDatosBancoAyuda': "Ask the management for them before transferring. We don't make them up: a transfer to the wrong account can't be undone.",
        'exp.informarPago': 'Report the fee payment',
        'exp.informarAyuda': 'Attach the transfer receipt',
        'exp.comprobante': 'Transfer receipt (photo or PDF)',
        'exp.elegirAyuda': 'Tap to pick it from your phone or gallery',
        'exp.importe': 'Amount you transferred',
        'exp.importePlaceholder': 'e.g. 85400',
        'exp.enviar': 'Send the receipt',
        'exp.enviando': 'Sending the receipt…',
        'exp.faltaComprobante': 'Attach the receipt first',
        'exp.misComprobantes': 'The receipts I sent',
        'exp.misComprobantesAyuda': 'Where each transfer stands',
        'exp.imputado': 'Credited',
        'exp.enRevision': 'Under review',
        'exp.comprobante1': 'Receipt',
        'exp.informado': 'Reported',
        'exp.reciente': 'Recent',
        'exp.historial': 'Earlier statements',
        'exp.historialAyuda': 'You can download any of them',
        'exp.periodo': 'Period',
        'exp.liquidacion': 'Fee statement',
        'exp.descargarPdf': 'Download',
        'exp.copiado': 'Copied',
        'exp.delEdificioNota': "This is the building's general statement, not your unit's. The detail is in the document.",
        // ── INTEGRANTES DE LA UNIDAD ──
        'int.volver': 'Back to home',
        'int.asignarTitulo': 'Add someone to the flat',
        'int.asignarAyuda': 'Family, tenants, guests, or whoever manages the property for you',
        'int.paso1': '1. What that person is in the flat',
        'int.rolFamiliar': 'Family or housemate',
        'int.rolInquilino': 'Tenant',
        'int.rolTurista': 'Guest for a few days',
        'int.rolAsistente': 'Whoever manages the property',
        'int.paso2': '2. The email they signed up with',
        'int.verificando': 'Looking…',
        'int.emailPlaceholder': 'e.g. user@email.com',
        'int.fechasEstadia': 'Dates of the stay',
        'int.checkin': 'Arrives',
        'int.checkout': 'Leaves',
        'int.turistaSinExpensas': "The guest doesn't see the fees. Only the doorbell, bookings, and the chat with Marcos.",
        'int.cesionGestion': 'Handing over management:',
        'int.cesionAyuda': "The flat joins the portfolio of whoever manages it. They'll be able to arrange stays, register guests, request moves, and open reports on your behalf.",
        'int.activosTitulo': 'Who has access',
        'int.activosAyuda': 'People with access to the flat',
        'int.cargando': 'Loading…',
        'int.reubicarTitulo': 'Move a guest to another flat',
        'int.huespedATrasladar': "Guest who's moving",
        'int.cargandoHuespedes': 'Loading guests…',
        'int.unidadDestino': 'Which flat they go to',
        'int.cargandoUnidades': 'Loading flats…',
        'int.motivoTraslado': "Why they're moving",
        'int.motivoPlaceholder': 'e.g. a water leak, or an urgent repair',
        'int.efectos': 'What happens when you confirm:',
        'int.confirmarReubicacion': 'Confirm the move',
        'int.reubicando': 'Moving…',
        'int.guardando': 'Saving…',
        'int.usuarioVerificado': 'We found this person in the app',
        'int.usuarioNoRegistrado': "We couldn't find anyone with that email",
        'int.usuarioNoRegistradoAyuda': 'They need to sign up in the app first, with their email and phone. Then you can add them to the flat.',
        'int.faltaUsuario': 'First enter the email of someone registered in the app.',
        'int.asignado': 'Done, they now have access to the flat.',
        'int.errorAsignar': 'That person could not be added.',
        'int.confirmarDesvincular': "Remove {nombre}'s access?",
        'int.desvinculado': 'Done, they no longer have access.',
        'int.errorConexion': "Couldn't connect. Please try again.",
        'int.elegirHuesped': 'Choose a guest…',
        'int.elegirDestino': 'Choose the destination flat…',
        'int.errorPortafolio': 'The portfolio could not be loaded',
        'int.faltaHuespedDestino': 'Pick the guest and the destination flat.',
        'int.reubicado': 'Done, the guest is in the other flat now.',
        'int.errorReubicar': 'The guest could not be moved.',
        'int.badgeTurista': 'Guest',
        'int.badgePropietario': 'Owner',
        'int.badgeAsistente': 'Manages the property',
        'int.badgeInquilino': 'Tenant',
        'int.badgeFamiliar': 'Family',
        'int.timbreOn': 'Doorbell on',
        'int.timbreOff': 'Doorbell off',
        'int.reubicarDepto': 'Move flat',
        'int.desvincular': 'Remove access',
        'int.huesped': 'Guest',
        'int.dueno': 'Owner',
        'int.del': 'From',
        'int.al': 'to',
        // ── AVISOS DEL EDIFICIO Y CHAT ──
        'nov.titulo': 'Building notices',
        'nov.subtitulo': 'What the management has announced at {edificio}',
        'nov.sinAvisos': 'No notices',
        'nov.sinAvisosAyuda': "When there's a water cut, pest control, or anything out of the ordinary, you'll see it here.",
        'chat.enLinea': 'Marcos is online',
        'chat.atencion': 'We answer at any hour',
        'chat.whatsapp': 'WhatsApp',
        'chat.saludo': "Hi {nombre}! I'm Marcos, the assistant at {edificio}. How can I help? You can ask me about the fees, report something broken, or ask for the building's details.",
        'chat.sug1': 'When are the fees due?',
        'chat.sug2': 'Water is leaking in the bathroom',
        'chat.sug3': 'Hours and rules for the party room',
        'chat.adjuntar': 'You can attach photos of the damage or a receipt',
        'chat.placeholder': 'Write to Marcos…',
        'chat.recibido': "Got it. I'll let you know as soon as there's news.",
        'chat.recibidoCorto': 'Got it, your message came through.',
        // ── RECLAMOS Y AVERÍAS ──
        'recl.titulo': 'Repairs and faults',
        'recl.reportar': 'Report something broken',
        'recl.enGestion': 'Being handled',
        'recl.resueltos': 'Resolved',
        'recl.misCasos': 'My cases',
        'recl.misReportados': 'What I reported',
        'recl.sinActivos': 'You have no open reports',
        'recl.sinActivosAyuda': 'If you see something broken in your flat or in the building, you can report it here.',
        'recl.areasComunes': 'Faults in shared areas',
        'recl.modalTitulo': 'Report a fault or something broken',
        'recl.rubro': 'Type of problem',
        'recl.rubroPlomeria': 'Plumbing',
        'recl.rubroElectricidad': 'Electrical',
        'recl.rubroAscensor': 'Lift',
        'recl.rubroPorton': 'Gate / entry',
        'recl.rubroGas': 'Gas',
        'recl.rubroLimpieza': 'Cleaning',
        'recl.ubicacion': 'Where the problem is',
        'recl.enMiDepto': 'In my flat ({depto})',
        'recl.areaComun': 'In a shared area',
        'recl.descripcion': "Tell us what's happening",
        'recl.descPlaceholder': "Describe it in detail. For example: water leaking under the sink, or the hallway light won't turn on.",
        'recl.foto': 'Photo of the damage (it helps a lot)',
        'recl.fotoBoton': 'Take a photo or pick one from your gallery',
        'recl.fotoAyuda': 'With a photo the technician can bring the right part',
        'recl.urgencia': 'Mark as a serious emergency',
        'recl.urgenciaAyuda': 'Flooding, a full power cut, a gas smell, or someone at risk',
        'recl.enviar': 'Send the report',
        'recl.enviando': 'Filing the report…',
        'recl.errorEnviar': 'The report could not be filed',
        'recl.estadoResuelto': 'Resolved',
        'recl.estadoEnCurso': 'In progress',
        'recl.estadoPendiente': 'Pending',
        'recl.averia': 'Fault',
        'recl.reciente': 'Just now',
        'recl.ampliar': 'Tap to enlarge',
        // ── ESPACIOS COMUNES (AMENITIES) ──
        'amen.titulo': 'Book a shared space',
        'amen.subtitulo': 'Shared spaces and hourly slots at {edificio}',
        'amen.misReservas': 'My bookings',
        'amen.nueva': 'New hourly booking',
        'amen.paso1': '1. Pick the space',
        'amen.paso2': '2. Pick the date',
        'amen.paso3': "3. Tap the hours you'll use (1-hour blocks)",
        'amen.libreOcupado': '🟩 Free · 🟥 Taken',
        'amen.motivoOpcional': 'Reason or number of people (optional)',
        'amen.motivoPlaceholder': 'e.g. family birthday, or a work meeting',
        'amen.confirmar': 'Confirm the booking',
        'amen.reglamento': 'Rules',
        'amen.sinCosto': 'Free',
        'amen.sinCostoEspacio': 'This space is free of charge',
        'amen.fijo': 'flat',
        'amen.pagoAprobado': 'Payment approved',
        'amen.pagoEnRevision': 'Payment under review',
        'amen.comprobanteObservado': 'Receipt queried',
        'amen.pagoPendiente': 'Payment pending',
        'amen.verComprobante': 'View the receipt',
        'amen.subirNuevo': 'Upload another receipt',
        'amen.subirComprobante': 'Upload the receipt',
        'amen.observacionAdmin': 'Note from the management:',
        'amen.observacionDefault': 'The previous receipt could not be verified. Please attach a clearer one.',
        'amen.cancelar': 'Cancel',
        'amen.informarPago': 'Report the booking payment',
        'amen.espacioAAbonar': 'Space to pay for:',
        'amen.datosBancarios': "Building's bank details",
        'amen.titular': 'Account holder',
        'amen.alias': 'Alias',
        'amen.copiar': 'Copy',
        'amen.adjuntar': 'Attach the receipt (photo or PDF)',
        'amen.elegirArchivo': 'Choose the photo or PDF of the receipt',
        'amen.elegirAyuda': 'Tap to pick it from your phone or gallery',
        'amen.montoAbonado': 'Amount you paid',
        'amen.montoPlaceholder': 'e.g. 15000',
        'amen.enviarComprobante': 'Send the receipt',
        'amen.arancel': 'Fee',
        'amen.tarifaFija': 'flat fee per booking',
        'amen.porHora': 'per hour booked',
        'amen.notaFija': 'The fee is the same no matter how many hours you pick.',
        'amen.notaPorHora': 'The total works itself out: the fee times the hours you pick.',
        'amen.notaTransferir': "Once you confirm the booking you'll be able to transfer to the building's account and attach the receipt from “My bookings”.",
        'amen.elegiFecha': 'Pick a date to see the free slots.',
        'amen.totalAAbonar': 'Total to pay',
        'amen.hora': 'hour',
        'amen.horas': 'hours',
        'amen.reservaHecha': '✓ Booked, from {desde} to {hasta}!',

        'error.generico': 'The action could not be completed.',
    },

    pt: {
        'nav.inicio': 'Início',
        'nav.chat': 'Marcos IA',
        'nav.porteria': 'Portaria',
        'nav.amenities': 'Áreas comuns',
        'nav.expensas': 'Condomínio',
        'nav.avisos': 'Avisos',

        'topbar.hola': 'Olá, {nombre}',
        'topbar.perfil': 'Meu Perfil',
        'topbar.tema': 'Mudar tema',
        'topbar.salir': 'Sair',
        'topbar.idioma': 'Idioma',

        'rol.propietario': 'Proprietário',
        'rol.inquilino': 'Inquilino',
        'rol.turista': 'Hóspede',
        'rol.asistente': 'Gestor',
        'rol.registrado': 'Sem unidade',

        'perfil.titulo': 'Meu Perfil',
        'perfil.bajada': 'Seus dados, suas unidades e seu acesso',
        'perfil.datos': 'Meus dados',
        'perfil.nombre': 'Nome',
        'perfil.apellido': 'Sobrenome',
        'perfil.telefono': 'Telefone de contato',
        'perfil.email': 'E-mail cadastrado',
        'perfil.emailNota': 'O e-mail é o que o proprietário usa para vincular você à unidade. Para trocá-lo, fale conosco pelo Marcos IA.',
        'perfil.guardar': 'Salvar alterações',
        'perfil.guardado': 'Dados salvos.',
        'perfil.sinNombre': 'O nome não pode ficar vazio',
        'perfil.idioma': 'Idioma do aplicativo',
        'perfil.idiomaNota': 'Muda o que você vê na tela. Pode trocar quando quiser.',
        'perfil.unidades': 'Minhas unidades',
        'perfil.unidadesNota': 'Escolha qual está vendo. Condomínio, chamados e áreas comuns seguem a unidade ativa.',
        'perfil.viendo': 'Vendo',
        'perfil.usarEsta': 'Usar esta',
        'perfil.sinExpensas': 'sem condomínio',
        'perfil.sinUnidades': 'Você ainda não tem nenhuma unidade vinculada. Peça ao proprietário do apartamento (ou à administração) que libere seu acesso com o e-mail {email} na aba Integrantes.',
        'perfil.estadia': 'Sua estadia',
        'perfil.desde': 'De',
        'perfil.hasta': 'Até',
        'perfil.pase': 'Passe QR temporário',
        'perfil.paseVence': 'Vence em {fecha} · mostre no totem da entrada',
        'perfil.acceso': 'Acesso e segurança',
        'perfil.accesoNota': 'Você também pode entrar com um código enviado por WhatsApp, sem senha.',
        'perfil.passActual': 'Senha atual',
        'perfil.passActualPlaceholder': 'Deixe vazio se nunca definiu uma',
        'perfil.passNueva': 'Nova senha',
        'perfil.passNuevaPlaceholder': 'Mínimo 6 caracteres',
        'perfil.passRepetir': 'Repetir a nova',
        'perfil.passRepetirPlaceholder': 'Igual à anterior',
        'perfil.cambiarPass': 'Trocar senha',
        'perfil.passCambiada': 'Senha atualizada.',
        'perfil.passDistintas': 'As duas senhas novas não coincidem.',
        'perfil.salir': 'Sair',
        'perfil.demo': 'Você está na sessão de teste. As alterações de dados e senha não são salvas até entrar com sua conta.',
        'perfil.sinCuenta': 'Entre com sua conta para trocar a senha',

        'inicio.expensasTab': 'Condomínio (ord. e extra)',
        'inicio.reservasTab': 'Reservas',
        'inicio.reclamosTab': 'Chamados',
        'inicio.totalAPagar': 'Total a pagar (mês atual)',
        'inicio.vencimiento': 'Vencimento: dia 10 · ordinárias e extraordinárias',
        'inicio.pagarExpensa': 'Pagar condomínio',
        'inicio.verRecibo': 'Ver recibo em PDF',
        'inicio.timbre': 'Minha campainha digital',
        'inicio.timbreActivo': 'Ativa · toca no seu celular',
        'inicio.timbreInactivo': 'Desligada',
        'inicio.noMolestar': 'Modo "Não perturbe"',
        'inicio.horarioSilencio': 'Horário de silêncio:',
        'inicio.timbreGuardado': 'Preferência da campainha salva',
        'inicio.accesosDirectos': 'Atalhos',
        'inicio.pasesQr': 'Passes QR',
        'inicio.porteriaQr': 'Portaria QR',
        'inicio.amenities': 'Áreas comuns',
        'inicio.integrantes': 'Integrantes',
        'inicio.instalarTitulo': 'Instalar o app no seu celular',
        'inicio.instalarBajada': 'Acesso rápido direto na sua tela',
        'inicio.instalar': 'Instalar',
        'inicio.asistenteTitulo': 'Assistente do condomínio 24/7',
        'inicio.asistenteBajada': 'Informe uma urgência, consulte o condomínio ou o regulamento.',
        'inicio.chatear': 'Conversar',
        'inicio.servicios': 'Serviços',
        'inicio.ascensor': 'Elevador principal',
        'inicio.ascensorEstado': 'Funcionando normalmente',
        'inicio.bombas': 'Bombas de água',
        'inicio.bombasEstado': 'Pressão normal',
        'inicio.porton': 'Portão da garagem',
        'inicio.portonEstado': 'Abertura automática',
        'inicio.novedades': 'Novidades do condomínio',
        'inicio.verTodas': 'Ver todas',
        'inicio.mantenimiento': 'Manutenção',
        'inicio.avisoTanques': 'Limpeza programada das caixas d’água',
        'inicio.avisoTanquesTexto': 'Quinta-feira, das 08:00 às 14:00. Haverá baixa pressão por um tempo.',
        'inicio.estadiaTemporal': 'Estadia temporária',
        'inicio.paseHuesped': 'Passe de hóspede ativo',
        'inicio.alojadoEn': 'Hospedado no apto',
        'inicio.huespedBienvenida': 'Você tem acesso a reservas de áreas comuns, campainha própria e Marcos IA 24/7.',
        'inicio.cuentaCreada': 'Conta criada',
        'inicio.sinDepto': 'Você ainda não tem nenhum apartamento vinculado.',
        'inicio.comoSigo': 'Como continuo?',
        'inicio.comoSigoTexto': 'Envie o e-mail com que você se cadastrou ({email}) para quem convidou você (proprietário, anfitrião ou administração) para liberar o acesso à unidade.',
        'inicio.asistencia24': 'Suporte 24h',

        'avisos.titulo': 'Avisos de {edificio}',
        'avisos.hasta': 'até {fecha}',
        'avisos.sinFecha': 'até novo aviso',
        'avisos.publicadoPor': 'Avisado por {quien} ({rol})',
        'avisos.reclamoAbierto': 'Chamado aberto, ainda sem solução',

        'expensa.sinCargar': 'O condomínio deste mês ainda não foi carregado.',
        'expensa.vence': 'Vence em {fecha}',
        'expensa.descargar': 'Baixar',
        'expensa.delEdificio': 'É o documento geral do prédio, não o da sua unidade.',
        'expensa.liquidacionEdificio': 'Balanço do prédio',

        // ── PASES QR ──
        'pases.titulo': 'Passes de visitante QR',
        'pases.nuevo': 'Novo passe QR',
        'pases.tabActivos': 'Passes ativos',
        'pases.tabHistorial': 'Histórico / vencidos',
        'pases.crearTitulo': 'Criar passe de visitante QR',
        'pases.nombreInvitado': 'Nome do visitante ou prestador',
        'pases.nombrePlaceholder': 'Ex.: Lucas González, ou o entregador',
        'pases.motivo': 'Motivo da visita',
        'pases.motivoDelivery': 'Entrega',
        'pases.motivoVisita': 'Visita',
        'pases.motivoEncomienda': 'Encomenda',
        'pases.motivoProveedor': 'Prestador',
        'pases.validez': 'Quanto tempo vale',
        'pases.validez2h': '2 horas (para uma entrega)',
        'pases.validez4h': '4 horas (para uma visita)',
        'pases.validezDia': 'O dia inteiro (até 23:59)',
        'pases.validezCustom': 'Data e hora que você escolher',
        'pases.desde': 'De',
        'pases.hasta': 'Até',
        'pases.recurrente': 'Que se repita (a diarista, por exemplo)',
        'pases.diasHabilitados': 'Dias da semana',
        'pases.horaEntrada': 'Hora de entrada',
        'pases.horaSalida': 'Hora de saída',
        'pases.generar': 'Gerar o passe e ver o código QR',
        'pases.generando': 'Gerando o passe…',
        'pases.habilitado': 'Passe habilitado',
        'pases.invitado': 'Visitante',
        'pases.compartirWhatsapp': 'Compartilhar no WhatsApp',
        'pases.copiarEnlace': 'Copiar o link do passe',
        'pases.sinActivos': 'Você não tem nenhum passe ativo neste momento.',
        'pases.activo': 'Ativo',
        'pases.codigo': 'Código',
        'pases.vence': 'Vence',
        'pases.verQr': 'Ver o QR / enviar',
        'pases.sinHistorial': 'Ainda não há passes anteriores.',
        'pases.validoHasta': 'Válido até',
        'pases.estadoUtilizado': 'Usado',
        'pases.estadoRevocado': 'Cancelado',
        'pases.estadoVencido': 'Vencido',
        'dia.lun': 'Seg',
        'dia.mar': 'Ter',
        'dia.mie': 'Qua',
        'dia.jue': 'Qui',
        'dia.vie': 'Sex',
        'dia.sab': 'Sáb',
        'dia.dom': 'Dom',

        // ── EXPENSAS ──
        'exp.titulo': 'Meu condomínio',
        'exp.liquidacionMes': 'Balanço do mês',
        'exp.digital': 'Digital',
        'exp.periodoVigente': 'Período atual',
        'exp.periodoEnProceso': 'Ainda sem período',
        'exp.totalAPagar': 'Total a pagar',
        'exp.venceEl': 'Vence em {fecha}',
        'exp.publicadoSinTotal': 'A administração publicou o documento deste período. O total ainda não foi carregado.',
        'exp.aunNoPublicada': 'A administração vai publicar o balanço deste mês nos próximos dias.',
        'exp.verDescargar': 'Ver ou baixar o balanço',
        'exp.pedirPorChat': 'Você pode pedir uma cópia ao Marcos no chat quando quiser.',
        'exp.datosTransferencia': 'Para transferir',
        'exp.cuentaOficial': 'Conta do condomínio',
        'exp.titular': 'Titular',
        'exp.banco': 'Banco',
        'exp.alias': 'Alias',
        'exp.copiar': 'Copiar',
        'exp.sinDatosBanco': 'Os dados da conta ainda não foram carregados',
        'exp.sinDatosBancoAyuda': 'Peça-os à administração antes de transferir. Não inventamos: uma transferência para a conta errada não pode ser desfeita.',
        'exp.informarPago': 'Informar o pagamento do condomínio',
        'exp.informarAyuda': 'Anexe o comprovante da transferência',
        'exp.comprobante': 'Comprovante da transferência (foto ou PDF)',
        'exp.elegirAyuda': 'Toque para escolher do seu celular ou da galeria',
        'exp.importe': 'Valor que você transferiu',
        'exp.importePlaceholder': 'Ex.: 85400',
        'exp.enviar': 'Enviar o comprovante',
        'exp.enviando': 'Enviando o comprovante…',
        'exp.faltaComprobante': 'Primeiro anexe o comprovante',
        'exp.misComprobantes': 'Os comprovantes que enviei',
        'exp.misComprobantesAyuda': 'Como ficou cada transferência',
        'exp.imputado': 'Baixado',
        'exp.enRevision': 'Em análise',
        'exp.comprobante1': 'Comprovante',
        'exp.informado': 'Informado',
        'exp.reciente': 'Recente',
        'exp.historial': 'Balanços anteriores',
        'exp.historialAyuda': 'Você pode baixar qualquer um',
        'exp.periodo': 'Período',
        'exp.liquidacion': 'Balanço do condomínio',
        'exp.descargarPdf': 'Baixar',
        'exp.copiado': 'Copiado',
        'exp.delEdificioNota': 'É o balanço geral do prédio, não o da sua unidade. O detalhe está no documento.',
        // ── INTEGRANTES DE LA UNIDAD ──
        'int.volver': 'Voltar ao início',
        'int.asignarTitulo': 'Adicionar alguém à unidade',
        'int.asignarAyuda': 'Familiares, inquilinos, hóspedes ou quem administra o imóvel para você',
        'int.paso1': '1. O que essa pessoa é no apartamento',
        'int.rolFamiliar': 'Familiar ou quem mora junto',
        'int.rolInquilino': 'Inquilino',
        'int.rolTurista': 'Hóspede por alguns dias',
        'int.rolAsistente': 'Quem administra o imóvel',
        'int.paso2': '2. E-mail com que se cadastrou',
        'int.verificando': 'Buscando…',
        'int.emailPlaceholder': 'ex.: usuario@email.com',
        'int.fechasEstadia': 'Datas da estadia',
        'int.checkin': 'Chega',
        'int.checkout': 'Sai',
        'int.turistaSinExpensas': 'O hóspede não vê o condomínio. Só a portaria, as reservas e o chat com o Marcos.',
        'int.cesionGestion': 'Cessão da administração:',
        'int.cesionAyuda': 'A unidade passa para a carteira de quem a administra. Vai poder combinar estadias, cadastrar hóspedes, pedir mudanças e abrir avisos em seu nome.',
        'int.activosTitulo': 'Quem tem acesso',
        'int.activosAyuda': 'Pessoas com acesso à unidade',
        'int.cargando': 'Carregando…',
        'int.reubicarTitulo': 'Mudar um hóspede para outra unidade',
        'int.huespedATrasladar': 'Hóspede que vai mudar',
        'int.cargandoHuespedes': 'Carregando hóspedes…',
        'int.unidadDestino': 'Para qual unidade vai',
        'int.cargandoUnidades': 'Carregando unidades…',
        'int.motivoTraslado': 'Por que está mudando',
        'int.motivoPlaceholder': 'Ex.: está vazando água, ou um reparo urgente',
        'int.efectos': 'O que acontece ao confirmar:',
        'int.confirmarReubicacion': 'Confirmar a mudança',
        'int.reubicando': 'Mudando…',
        'int.guardando': 'Salvando…',
        'int.usuarioVerificado': 'Encontramos essa pessoa no app',
        'int.usuarioNoRegistrado': 'Não encontramos ninguém com esse e-mail',
        'int.usuarioNoRegistradoAyuda': 'A pessoa precisa se cadastrar no app primeiro, com e-mail e telefone. Depois você pode adicioná-la à unidade.',
        'int.faltaUsuario': 'Primeiro coloque o e-mail de alguém cadastrado no app.',
        'int.asignado': 'Pronto, agora tem acesso à unidade.',
        'int.errorAsignar': 'Não foi possível adicionar essa pessoa.',
        'int.confirmarDesvincular': 'Tirar o acesso de {nombre}?',
        'int.desvinculado': 'Pronto, não tem mais acesso.',
        'int.errorConexion': 'Não foi possível conectar. Tente de novo.',
        'int.elegirHuesped': 'Escolher hóspede…',
        'int.elegirDestino': 'Escolher a unidade de destino…',
        'int.errorPortafolio': 'Não foi possível consultar a carteira',
        'int.faltaHuespedDestino': 'Escolha o hóspede e a unidade de destino.',
        'int.reubicado': 'Pronto, o hóspede já está na outra unidade.',
        'int.errorReubicar': 'Não foi possível mudar o hóspede.',
        'int.badgeTurista': 'Hóspede',
        'int.badgePropietario': 'Proprietário',
        'int.badgeAsistente': 'Administra o imóvel',
        'int.badgeInquilino': 'Inquilino',
        'int.badgeFamiliar': 'Familiar',
        'int.timbreOn': 'Porteiro ligado',
        'int.timbreOff': 'Porteiro desligado',
        'int.reubicarDepto': 'Mudar de unidade',
        'int.desvincular': 'Tirar acesso',
        'int.huesped': 'Hóspede',
        'int.dueno': 'Dono',
        'int.del': 'De',
        'int.al': 'até',
        // ── AVISOS DEL EDIFICIO Y CHAT ──
        'nov.titulo': 'Avisos do prédio',
        'nov.subtitulo': 'O que a administração comunicou em {edificio}',
        'nov.sinAvisos': 'Não há avisos',
        'nov.sinAvisosAyuda': 'Quando houver falta de água, dedetização ou algo fora do comum, você vai ver aqui.',
        'chat.enLinea': 'Marcos está online',
        'chat.atencion': 'Respondemos a qualquer hora',
        'chat.whatsapp': 'WhatsApp',
        'chat.saludo': 'Olá {nombre}! Sou o Marcos, o assistente de {edificio}. Como posso ajudar? Você pode me perguntar sobre o condomínio, avisar de algo quebrado, ou pedir dados do prédio.',
        'chat.sug1': 'Quando vence o condomínio?',
        'chat.sug2': 'Está vazando água no banheiro',
        'chat.sug3': 'Horário e regras do salão de festas',
        'chat.adjuntar': 'Você pode anexar fotos de algo quebrado ou um comprovante',
        'chat.placeholder': 'Escreva para o Marcos…',
        'chat.recibido': 'Pronto, anotei. Qualquer novidade eu te aviso.',
        'chat.recibidoCorto': 'Pronto, recebi sua mensagem.',
        // ── RECLAMOS Y AVERÍAS ──
        'recl.titulo': 'Reparos e avarias',
        'recl.reportar': 'Avisar de algo quebrado',
        'recl.enGestion': 'Em andamento',
        'recl.resueltos': 'Resolvidos',
        'recl.misCasos': 'Meus casos',
        'recl.misReportados': 'O que eu avisei',
        'recl.sinActivos': 'Você não tem avisos abertos',
        'recl.sinActivosAyuda': 'Se vir algo quebrado no seu apartamento ou no prédio, pode avisar aqui.',
        'recl.areasComunes': 'Avarias nas áreas comuns',
        'recl.modalTitulo': 'Avisar de uma avaria ou algo quebrado',
        'recl.rubro': 'Tipo de problema',
        'recl.rubroPlomeria': 'Encanamento',
        'recl.rubroElectricidad': 'Elétrica',
        'recl.rubroAscensor': 'Elevador',
        'recl.rubroPorton': 'Portão / acesso',
        'recl.rubroGas': 'Gás',
        'recl.rubroLimpieza': 'Limpeza',
        'recl.ubicacion': 'Onde está o problema',
        'recl.enMiDepto': 'No meu apartamento ({depto})',
        'recl.areaComun': 'Em uma área comum',
        'recl.descripcion': 'Conte o que está acontecendo',
        'recl.descPlaceholder': 'Descreva com detalhe. Por exemplo: está vazando água embaixo da pia, ou a luz do corredor não acende.',
        'recl.foto': 'Foto do estrago (ajuda muito)',
        'recl.fotoBoton': 'Tirar uma foto ou escolher da galeria',
        'recl.fotoAyuda': 'Com a foto o técnico pode trazer a peça certa',
        'recl.urgencia': 'Marcar como emergência grave',
        'recl.urgenciaAyuda': 'Alagamento, falta de luz geral, cheiro de gás ou risco para alguém',
        'recl.enviar': 'Enviar o aviso',
        'recl.enviando': 'Registrando o aviso…',
        'recl.errorEnviar': 'Não foi possível registrar o aviso',
        'recl.estadoResuelto': 'Resolvido',
        'recl.estadoEnCurso': 'Em andamento',
        'recl.estadoPendiente': 'Pendente',
        'recl.averia': 'Avaria',
        'recl.reciente': 'Agora',
        'recl.ampliar': 'Toque para ampliar',
        // ── ESPACIOS COMUNES (AMENITIES) ──
        'amen.titulo': 'Reservar espaço comum',
        'amen.subtitulo': 'Espaços comuns e horários por hora em {edificio}',
        'amen.misReservas': 'Minhas reservas',
        'amen.nueva': 'Nova reserva por horas',
        'amen.paso1': '1. Escolha o espaço',
        'amen.paso2': '2. Escolha a data',
        'amen.paso3': '3. Toque nas horas que vai usar (blocos de 1 hora)',
        'amen.libreOcupado': '🟩 Livre · 🟥 Ocupado',
        'amen.motivoOpcional': 'Motivo ou quantidade de pessoas (opcional)',
        'amen.motivoPlaceholder': 'Ex.: aniversário em família, ou reunião de trabalho',
        'amen.confirmar': 'Confirmar a reserva',
        'amen.reglamento': 'Regulamento',
        'amen.sinCosto': 'Sem custo',
        'amen.sinCostoEspacio': 'Este espaço não tem custo',
        'amen.fijo': 'fixo',
        'amen.pagoAprobado': 'Pagamento aprovado',
        'amen.pagoEnRevision': 'Pagamento em análise',
        'amen.comprobanteObservado': 'Comprovante com ressalva',
        'amen.pagoPendiente': 'Pagamento pendente',
        'amen.verComprobante': 'Ver o comprovante',
        'amen.subirNuevo': 'Enviar outro comprovante',
        'amen.subirComprobante': 'Enviar o comprovante',
        'amen.observacionAdmin': 'Observação da administração:',
        'amen.observacionDefault': 'O comprovante anterior não pôde ser verificado. Por favor, anexe um que se leia bem.',
        'amen.cancelar': 'Cancelar',
        'amen.informarPago': 'Informar o pagamento da reserva',
        'amen.espacioAAbonar': 'Espaço a pagar:',
        'amen.datosBancarios': 'Dados bancários do condomínio',
        'amen.titular': 'Titular',
        'amen.alias': 'Alias',
        'amen.copiar': 'Copiar',
        'amen.adjuntar': 'Anexar o comprovante (foto ou PDF)',
        'amen.elegirArchivo': 'Escolher a foto ou o PDF do comprovante',
        'amen.elegirAyuda': 'Toque para escolher do seu celular ou da galeria',
        'amen.montoAbonado': 'Valor que você pagou',
        'amen.montoPlaceholder': 'Ex.: 15000',
        'amen.enviarComprobante': 'Enviar o comprovante',
        'amen.arancel': 'Taxa',
        'amen.tarifaFija': 'taxa fixa por reserva',
        'amen.porHora': 'por hora reservada',
        'amen.notaFija': 'A taxa é a mesma, não importa quantas horas você escolher.',
        'amen.notaPorHora': 'O total é calculado sozinho: a taxa vezes as horas que você escolher.',
        'amen.notaTransferir': 'Quando confirmar a reserva você vai poder transferir para a conta do condomínio e anexar o comprovante em “Minhas reservas”.',
        'amen.elegiFecha': 'Escolha uma data para ver os horários livres.',
        'amen.totalAAbonar': 'Total a pagar',
        'amen.hora': 'hora',
        'amen.horas': 'horas',
        'amen.reservaHecha': '✓ Reserva feita, de {desde} às {hasta}!',

        'error.generico': 'Não foi possível concluir a ação.',
    },

    fr: {
        'nav.inicio': 'Accueil',
        'nav.chat': 'Marcos IA',
        'nav.porteria': 'Entrée',
        'nav.amenities': 'Espaces communs',
        'nav.expensas': 'Charges',
        'nav.avisos': 'Avis',

        'topbar.hola': 'Bonjour, {nombre}',
        'topbar.perfil': 'Mon Profil',
        'topbar.tema': 'Changer de thème',
        'topbar.salir': 'Se déconnecter',
        'topbar.idioma': 'Langue',

        'rol.propietario': 'Propriétaire',
        'rol.inquilino': 'Locataire',
        'rol.turista': 'Invité',
        'rol.asistente': 'Gestionnaire',
        'rol.registrado': 'Sans logement',

        'perfil.titulo': 'Mon Profil',
        'perfil.bajada': 'Vos informations, vos logements et votre accès',
        'perfil.datos': 'Mes informations',
        'perfil.nombre': 'Prénom',
        'perfil.apellido': 'Nom',
        'perfil.telefono': 'Téléphone de contact',
        'perfil.email': 'E-mail enregistré',
        'perfil.emailNota': "L'e-mail est ce que le propriétaire utilise pour vous rattacher au logement. Pour le changer, écrivez-nous via Marcos IA.",
        'perfil.guardar': 'Enregistrer',
        'perfil.guardado': 'Informations enregistrées.',
        'perfil.sinNombre': 'Le prénom ne peut pas être vide',
        'perfil.idioma': "Langue de l'application",
        'perfil.idiomaNota': 'Change ce que vous voyez à l’écran. Vous pouvez la changer quand vous voulez.',
        'perfil.unidades': 'Mes logements',
        'perfil.unidadesNota': 'Choisissez celui que vous consultez. Charges, demandes et espaces communs suivent le logement actif.',
        'perfil.viendo': 'En cours',
        'perfil.usarEsta': 'Utiliser celui-ci',
        'perfil.sinExpensas': 'sans charges',
        'perfil.sinUnidades': "Vous n'avez encore aucun logement rattaché. Demandez au propriétaire (ou à la gestion) de vous ajouter avec votre e-mail {email} depuis l'onglet Occupants.",
        'perfil.estadia': 'Votre séjour',
        'perfil.desde': 'Du',
        'perfil.hasta': 'Au',
        'perfil.pase': 'Pass QR temporaire',
        'perfil.paseVence': "Expire le {fecha} · présentez-le à la borne d'entrée",
        'perfil.acceso': 'Accès et sécurité',
        'perfil.accesoNota': 'Vous pouvez aussi vous connecter avec un code reçu par WhatsApp, sans mot de passe.',
        'perfil.passActual': 'Mot de passe actuel',
        'perfil.passActualPlaceholder': "Laissez vide si vous n'en avez jamais défini",
        'perfil.passNueva': 'Nouveau mot de passe',
        'perfil.passNuevaPlaceholder': 'Au moins 6 caractères',
        'perfil.passRepetir': 'Répéter le nouveau',
        'perfil.passRepetirPlaceholder': 'Identique au précédent',
        'perfil.cambiarPass': 'Changer le mot de passe',
        'perfil.passCambiada': 'Mot de passe mis à jour.',
        'perfil.passDistintas': 'Les deux nouveaux mots de passe ne correspondent pas.',
        'perfil.salir': 'Se déconnecter',
        'perfil.demo': "Vous êtes dans la session de démonstration. Les modifications ne sont pas enregistrées tant que vous ne vous connectez pas avec votre compte.",
        'perfil.sinCuenta': 'Connectez-vous avec votre compte pour changer le mot de passe',

        'inicio.expensasTab': 'Charges (ord. et extra.)',
        'inicio.reservasTab': 'Réservations',
        'inicio.reclamosTab': 'Demandes',
        'inicio.totalAPagar': 'Total à payer (mois en cours)',
        'inicio.vencimiento': 'Échéance : le 10 du mois · ordinaires et extraordinaires',
        'inicio.pagarExpensa': 'Payer',
        'inicio.verRecibo': 'Voir le reçu PDF',
        'inicio.timbre': 'Ma sonnette numérique',
        'inicio.timbreActivo': 'Active · sonne sur votre téléphone',
        'inicio.timbreInactivo': 'Désactivée',
        'inicio.noMolestar': 'Mode « Ne pas déranger »',
        'inicio.horarioSilencio': 'Heures de silence :',
        'inicio.timbreGuardado': 'Préférence de sonnette enregistrée',
        'inicio.accesosDirectos': 'Raccourcis',
        'inicio.pasesQr': 'Pass QR',
        'inicio.porteriaQr': 'Entrée QR',
        'inicio.amenities': 'Espaces communs',
        'inicio.integrantes': 'Occupants',
        'inicio.instalarTitulo': "Installer l'app sur votre téléphone",
        'inicio.instalarBajada': "Accès rapide sur votre écran d'accueil",
        'inicio.instalar': 'Installer',
        'inicio.asistenteTitulo': 'Assistance immeuble 24/7',
        'inicio.asistenteBajada': 'Signalez une urgence, consultez les charges ou le règlement.',
        'inicio.chatear': 'Discuter',
        'inicio.servicios': 'Services',
        'inicio.ascensor': 'Ascenseur principal',
        'inicio.ascensorEstado': 'En service normal',
        'inicio.bombas': 'Pompes à eau',
        'inicio.bombasEstado': 'Pression normale',
        'inicio.porton': 'Portail du garage',
        'inicio.portonEstado': 'Ouverture automatique',
        'inicio.novedades': "Actualités de l'immeuble",
        'inicio.verTodas': 'Tout voir',
        'inicio.mantenimiento': 'Maintenance',
        'inicio.avisoTanques': 'Nettoyage programmé des réservoirs',
        'inicio.avisoTanquesTexto': 'Jeudi de 08h00 à 14h00. Basse pression pendant un moment.',
        'inicio.estadiaTemporal': 'Séjour temporaire',
        'inicio.paseHuesped': 'Pass invité actif',
        'inicio.alojadoEn': 'Logé au logement',
        'inicio.huespedBienvenida': 'Vous avez accès aux réservations, à votre sonnette et à Marcos IA 24/7.',
        'inicio.cuentaCreada': 'Compte créé',
        'inicio.sinDepto': 'Aucun logement ne vous est encore attribué.',
        'inicio.comoSigo': 'Et maintenant ?',
        'inicio.comoSigoTexto': "Envoyez l'e-mail avec lequel vous vous êtes inscrit ({email}) à la personne qui vous a invité (propriétaire, hôte ou gestion) pour qu'elle vous donne accès au logement.",
        'inicio.asistencia24': 'Assistance 24h/24',

        'avisos.titulo': 'Avis de {edificio}',
        'avisos.hasta': "jusqu'au {fecha}",
        'avisos.sinFecha': 'jusqu’à nouvel ordre',
        'avisos.publicadoPor': 'Signalé par {quien} ({rol})',
        'avisos.reclamoAbierto': 'Demande ouverte, pas encore résolue',

        'expensa.sinCargar': 'Les charges de ce mois ne sont pas encore déposées.',
        'expensa.vence': 'Échéance le {fecha}',
        'expensa.descargar': 'Télécharger',
        'expensa.delEdificio': "C'est le document général de l'immeuble, pas celui de votre logement.",
        'expensa.liquidacionEdificio': "Décompte de l'immeuble",

        // ── PASES QR ──
        'pases.titulo': 'Laissez-passer QR',
        'pases.nuevo': 'Nouveau laissez-passer',
        'pases.tabActivos': 'Laissez-passer actifs',
        'pases.tabHistorial': 'Historique / expirés',
        'pases.crearTitulo': 'Créer un laissez-passer QR',
        'pases.nombreInvitado': "Nom de l'invité ou du prestataire",
        'pases.nombrePlaceholder': 'Ex. : Lucas González, ou le livreur',
        'pases.motivo': 'Motif de la visite',
        'pases.motivoDelivery': 'Livraison',
        'pases.motivoVisita': 'Visite',
        'pases.motivoEncomienda': 'Colis',
        'pases.motivoProveedor': 'Prestataire',
        'pases.validez': 'Durée de validité',
        'pases.validez2h': '2 heures (pour une livraison)',
        'pases.validez4h': '4 heures (pour une visite)',
        'pases.validezDia': "Toute la journée (jusqu'à 23 h 59)",
        'pases.validezCustom': 'Une date et une heure au choix',
        'pases.desde': 'À partir de',
        'pases.hasta': "Jusqu'à",
        'pases.recurrente': "Qu'il se répète (la personne de ménage, par exemple)",
        'pases.diasHabilitados': 'Jours de la semaine',
        'pases.horaEntrada': "Heure d'arrivée",
        'pases.horaSalida': 'Heure de départ',
        'pases.generar': 'Créer le laissez-passer et voir le QR',
        'pases.generando': 'Création du laissez-passer…',
        'pases.habilitado': 'Laissez-passer activé',
        'pases.invitado': 'Invité',
        'pases.compartirWhatsapp': 'Partager sur WhatsApp',
        'pases.copiarEnlace': 'Copier le lien du laissez-passer',
        'pases.sinActivos': "Vous n'avez aucun laissez-passer actif en ce moment.",
        'pases.activo': 'Actif',
        'pases.codigo': 'Code',
        'pases.vence': 'Expire',
        'pases.verQr': 'Voir le QR / envoyer',
        'pases.sinHistorial': 'Aucun laissez-passer antérieur pour le moment.',
        'pases.validoHasta': "Valable jusqu'au",
        'pases.estadoUtilizado': 'Utilisé',
        'pases.estadoRevocado': 'Annulé',
        'pases.estadoVencido': 'Expiré',
        'dia.lun': 'Lun',
        'dia.mar': 'Mar',
        'dia.mie': 'Mer',
        'dia.jue': 'Jeu',
        'dia.vie': 'Ven',
        'dia.sab': 'Sam',
        'dia.dom': 'Dim',

        // ── EXPENSAS ──
        'exp.titulo': 'Mes charges',
        'exp.liquidacionMes': 'Décompte du mois',
        'exp.digital': 'Numérique',
        'exp.periodoVigente': 'Période en cours',
        'exp.periodoEnProceso': 'Pas encore de période',
        'exp.totalAPagar': 'Total à payer',
        'exp.venceEl': 'Échéance le {fecha}',
        'exp.publicadoSinTotal': "L'administration a publié le document de cette période. Le total n'est pas encore saisi.",
        'exp.aunNoPublicada': "L'administration publiera le décompte de ce mois dans les prochains jours.",
        'exp.verDescargar': 'Voir ou télécharger le décompte',
        'exp.pedirPorChat': 'Vous pouvez demander une copie à Marcos dans le chat quand vous voulez.',
        'exp.datosTransferencia': 'Pour virer',
        'exp.cuentaOficial': 'Compte de la copropriété',
        'exp.titular': 'Titulaire',
        'exp.banco': 'Banque',
        'exp.alias': 'Alias',
        'exp.copiar': 'Copier',
        'exp.sinDatosBanco': 'Les coordonnées du compte ne sont pas encore saisies',
        'exp.sinDatosBancoAyuda': "Demandez-les à l'administration avant de virer. Nous ne les inventons pas : un virement sur le mauvais compte ne peut pas être annulé.",
        'exp.informarPago': 'Signaler le paiement des charges',
        'exp.informarAyuda': 'Joignez le justificatif du virement',
        'exp.comprobante': 'Justificatif du virement (photo ou PDF)',
        'exp.elegirAyuda': 'Touchez pour le choisir depuis votre téléphone ou la galerie',
        'exp.importe': 'Montant que vous avez viré',
        'exp.importePlaceholder': 'Ex. : 85400',
        'exp.enviar': 'Envoyer le justificatif',
        'exp.enviando': 'Envoi du justificatif…',
        'exp.faltaComprobante': "Joignez d'abord le justificatif",
        'exp.misComprobantes': "Les justificatifs que j'ai envoyés",
        'exp.misComprobantesAyuda': 'Où en est chaque virement',
        'exp.imputado': 'Imputé',
        'exp.enRevision': 'En cours de vérification',
        'exp.comprobante1': 'Justificatif',
        'exp.informado': 'Signalé',
        'exp.reciente': 'Récent',
        'exp.historial': 'Décomptes précédents',
        'exp.historialAyuda': "Vous pouvez télécharger n'importe lequel",
        'exp.periodo': 'Période',
        'exp.liquidacion': 'Décompte de charges',
        'exp.descargarPdf': 'Télécharger',
        'exp.copiado': 'Copié',
        'exp.delEdificioNota': "C'est le décompte général de l'immeuble, pas celui de votre logement. Le détail est dans le document.",
        // ── INTEGRANTES DE LA UNIDAD ──
        'int.volver': "Retour à l'accueil",
        'int.asignarTitulo': "Ajouter quelqu'un au logement",
        'int.asignarAyuda': 'Famille, locataires, invités, ou la personne qui gère le bien pour vous',
        'int.paso1': "1. Ce qu'est cette personne dans le logement",
        'int.rolFamiliar': 'Famille ou colocataire',
        'int.rolInquilino': 'Locataire',
        'int.rolTurista': 'Invité pour quelques jours',
        'int.rolAsistente': 'La personne qui gère le bien',
        'int.paso2': "2. L'e-mail utilisé à l'inscription",
        'int.verificando': 'Recherche…',
        'int.emailPlaceholder': 'ex. : utilisateur@email.com',
        'int.fechasEstadia': 'Dates du séjour',
        'int.checkin': 'Arrivée',
        'int.checkout': 'Départ',
        'int.turistaSinExpensas': "L'invité ne voit pas les charges. Seulement l'interphone, les réservations et le chat avec Marcos.",
        'int.cesionGestion': 'Délégation de la gestion :',
        'int.cesionAyuda': 'Le logement rejoint le portefeuille de la personne qui le gère. Elle pourra organiser les séjours, enregistrer des invités, demander des relogements et ouvrir des signalements en votre nom.',
        'int.activosTitulo': 'Qui a accès',
        'int.activosAyuda': 'Personnes ayant accès au logement',
        'int.cargando': 'Chargement…',
        'int.reubicarTitulo': 'Déplacer un invité vers un autre logement',
        'int.huespedATrasladar': 'Invité qui déménage',
        'int.cargandoHuespedes': 'Chargement des invités…',
        'int.unidadDestino': 'Vers quel logement',
        'int.cargandoUnidades': 'Chargement des logements…',
        'int.motivoTraslado': 'Pourquoi il déménage',
        'int.motivoPlaceholder': "Ex. : une fuite d'eau, ou une réparation urgente",
        'int.efectos': 'Ce qui se passe à la confirmation :',
        'int.confirmarReubicacion': 'Confirmer le déplacement',
        'int.reubicando': 'Déplacement…',
        'int.guardando': 'Enregistrement…',
        'int.usuarioVerificado': "Nous avons trouvé cette personne dans l'application",
        'int.usuarioNoRegistrado': 'Aucune personne trouvée avec cet e-mail',
        'int.usuarioNoRegistradoAyuda': "La personne doit d'abord s'inscrire dans l'application, avec son e-mail et son téléphone. Ensuite vous pourrez l'ajouter au logement.",
        'int.faltaUsuario': "Saisissez d'abord l'e-mail d'une personne inscrite dans l'application.",
        'int.asignado': "C'est fait, elle a désormais accès au logement.",
        'int.errorAsignar': "Cette personne n'a pas pu être ajoutée.",
        'int.confirmarDesvincular': "Retirer l'accès de {nombre} ?",
        'int.desvinculado': "C'est fait, elle n'a plus accès.",
        'int.errorConexion': 'Connexion impossible. Réessayez.',
        'int.elegirHuesped': 'Choisir un invité…',
        'int.elegirDestino': 'Choisir le logement de destination…',
        'int.errorPortafolio': "Le portefeuille n'a pas pu être consulté",
        'int.faltaHuespedDestino': "Choisissez l'invité et le logement de destination.",
        'int.reubicado': "C'est fait, l'invité est dans l'autre logement.",
        'int.errorReubicar': "L'invité n'a pas pu être déplacé.",
        'int.badgeTurista': 'Invité',
        'int.badgePropietario': 'Propriétaire',
        'int.badgeAsistente': 'Gère le bien',
        'int.badgeInquilino': 'Locataire',
        'int.badgeFamiliar': 'Famille',
        'int.timbreOn': 'Interphone activé',
        'int.timbreOff': 'Interphone désactivé',
        'int.reubicarDepto': 'Changer de logement',
        'int.desvincular': "Retirer l'accès",
        'int.huesped': 'Invité',
        'int.dueno': 'Propriétaire',
        'int.del': 'Du',
        'int.al': 'au',
        // ── AVISOS DEL EDIFICIO Y CHAT ──
        'nov.titulo': "Avis de l'immeuble",
        'nov.subtitulo': "Ce que l'administration a annoncé à {edificio}",
        'nov.sinAvisos': 'Aucun avis',
        'nov.sinAvisosAyuda': "En cas de coupure d'eau, de désinsectisation ou de quelque chose d'inhabituel, vous le verrez ici.",
        'chat.enLinea': 'Marcos est en ligne',
        'chat.atencion': 'Nous répondons à toute heure',
        'chat.whatsapp': 'WhatsApp',
        'chat.saludo': "Bonjour {nombre} ! Je suis Marcos, l'assistant de {edificio}. Comment puis-je vous aider ? Vous pouvez me demander pour les charges, signaler quelque chose de cassé, ou demander les coordonnées de l'immeuble.",
        'chat.sug1': 'Quand les charges sont-elles dues ?',
        'chat.sug2': "Il y a une fuite d'eau dans la salle de bain",
        'chat.sug3': 'Horaires et règlement de la salle commune',
        'chat.adjuntar': 'Vous pouvez joindre des photos des dégâts ou un justificatif',
        'chat.placeholder': 'Écrivez à Marcos…',
        'chat.recibido': "C'est noté. Je vous préviens dès qu'il y a du nouveau.",
        'chat.recibidoCorto': "C'est bien reçu.",
        // ── RECLAMOS Y AVERÍAS ──
        'recl.titulo': 'Pannes et réparations',
        'recl.reportar': 'Signaler quelque chose de cassé',
        'recl.enGestion': 'En cours de traitement',
        'recl.resueltos': 'Résolus',
        'recl.misCasos': 'Mes dossiers',
        'recl.misReportados': "Ce que j'ai signalé",
        'recl.sinActivos': "Vous n'avez aucun signalement en cours",
        'recl.sinActivosAyuda': "Si vous voyez quelque chose de cassé dans votre logement ou dans l'immeuble, signalez-le ici.",
        'recl.areasComunes': 'Pannes dans les parties communes',
        'recl.modalTitulo': 'Signaler une panne ou quelque chose de cassé',
        'recl.rubro': 'Type de problème',
        'recl.rubroPlomeria': 'Plomberie',
        'recl.rubroElectricidad': 'Électricité',
        'recl.rubroAscensor': 'Ascenseur',
        'recl.rubroPorton': 'Portail / accès',
        'recl.rubroGas': 'Gaz',
        'recl.rubroLimpieza': 'Ménage',
        'recl.ubicacion': 'Où se trouve le problème',
        'recl.enMiDepto': 'Dans mon logement ({depto})',
        'recl.areaComun': 'Dans une partie commune',
        'recl.descripcion': 'Racontez ce qui se passe',
        'recl.descPlaceholder': "Décrivez-le en détail. Par exemple : une fuite d'eau sous l'évier, ou la lumière du couloir ne s'allume pas.",
        'recl.foto': 'Photo des dégâts (ça aide beaucoup)',
        'recl.fotoBoton': 'Prendre une photo ou en choisir une dans la galerie',
        'recl.fotoAyuda': 'Avec une photo, le technicien peut apporter la bonne pièce',
        'recl.urgencia': 'Signaler comme urgence grave',
        'recl.urgenciaAyuda': "Inondation, coupure de courant générale, odeur de gaz ou risque pour quelqu'un",
        'recl.enviar': 'Envoyer le signalement',
        'recl.enviando': 'Enregistrement du signalement…',
        'recl.errorEnviar': "Le signalement n'a pas pu être enregistré",
        'recl.estadoResuelto': 'Résolu',
        'recl.estadoEnCurso': 'En cours',
        'recl.estadoPendiente': 'En attente',
        'recl.averia': 'Panne',
        'recl.reciente': "À l'instant",
        'recl.ampliar': 'Touchez pour agrandir',
        // ── ESPACIOS COMUNES (AMENITIES) ──
        'amen.titulo': 'Réserver un espace commun',
        'amen.subtitulo': 'Espaces communs et créneaux horaires à {edificio}',
        'amen.misReservas': 'Mes réservations',
        'amen.nueva': "Nouvelle réservation à l'heure",
        'amen.paso1': "1. Choisissez l'espace",
        'amen.paso2': '2. Choisissez la date',
        'amen.paso3': "3. Touchez les heures que vous allez utiliser (blocs d'1 heure)",
        'amen.libreOcupado': '🟩 Libre · 🟥 Occupé',
        'amen.motivoOpcional': 'Motif ou nombre de personnes (facultatif)',
        'amen.motivoPlaceholder': 'Ex. : anniversaire en famille, ou réunion de travail',
        'amen.confirmar': 'Confirmer la réservation',
        'amen.reglamento': 'Règlement',
        'amen.sinCosto': 'Gratuit',
        'amen.sinCostoEspacio': 'Cet espace est gratuit',
        'amen.fijo': 'forfait',
        'amen.pagoAprobado': 'Paiement approuvé',
        'amen.pagoEnRevision': 'Paiement en cours de vérification',
        'amen.comprobanteObservado': 'Justificatif à revoir',
        'amen.pagoPendiente': 'Paiement en attente',
        'amen.verComprobante': 'Voir le justificatif',
        'amen.subirNuevo': 'Envoyer un autre justificatif',
        'amen.subirComprobante': 'Envoyer le justificatif',
        'amen.observacionAdmin': "Remarque de l'administration :",
        'amen.observacionDefault': "Le justificatif précédent n'a pas pu être vérifié. Merci d'en joindre un plus lisible.",
        'amen.cancelar': 'Annuler',
        'amen.informarPago': 'Signaler le paiement de la réservation',
        'amen.espacioAAbonar': 'Espace à payer :',
        'amen.datosBancarios': 'Coordonnées bancaires de la copropriété',
        'amen.titular': 'Titulaire',
        'amen.alias': 'Alias',
        'amen.copiar': 'Copier',
        'amen.adjuntar': 'Joindre le justificatif (photo ou PDF)',
        'amen.elegirArchivo': 'Choisir la photo ou le PDF du justificatif',
        'amen.elegirAyuda': 'Touchez pour le choisir depuis votre téléphone ou la galerie',
        'amen.montoAbonado': 'Montant que vous avez payé',
        'amen.montoPlaceholder': 'Ex. : 15000',
        'amen.enviarComprobante': 'Envoyer le justificatif',
        'amen.arancel': 'Tarif',
        'amen.tarifaFija': 'forfait par réservation',
        'amen.porHora': 'par heure réservée',
        'amen.notaFija': "Le tarif est le même, quel que soit le nombre d'heures choisi.",
        'amen.notaPorHora': 'Le total se calcule tout seul : le tarif multiplié par les heures choisies.',
        'amen.notaTransferir': 'Une fois la réservation confirmée, vous pourrez virer le montant sur le compte de la copropriété et joindre le justificatif depuis “Mes réservations”.',
        'amen.elegiFecha': 'Choisissez une date pour voir les créneaux libres.',
        'amen.totalAAbonar': 'Total à payer',
        'amen.hora': 'heure',
        'amen.horas': 'heures',
        'amen.reservaHecha': '✓ Réservé, de {desde} à {hasta} !',

        'error.generico': "L'action n'a pas pu être effectuée.",
    },
};

// Normaliza lo que venga: 'PT-BR', 'en-US', 'pt_BR' y 'pt' son todos el mismo idioma.
// Uno que no tenemos cae al castellano en vez de romper.
function normalizarIdioma(valor) {
    const base = String(valor || '').trim().toLowerCase().replace('_', '-').split('-')[0];
    return TEXTOS[base] ? base : IDIOMA_POR_DEFECTO;
}

// El idioma del navegador, para el que todavía no eligió ninguno. Se lee de `Accept-Language`,
// que llega ordenado por preferencia: se toma el primero que sepamos hablar.
function idiomaDelNavegador(cabecera) {
    for (const trozo of String(cabecera || '').split(',')) {
        const base = trozo.split(';')[0].trim().toLowerCase().split('-')[0];
        if (TEXTOS[base]) return base;
    }
    return IDIOMA_POR_DEFECTO;
}

// `{nombre}` y `{email}` se reemplazan por lo que se le pase. El orden de las palabras cambia
// entre idiomas, así que el hueco va adentro del texto traducido y no se concatena afuera.
function interpolar(texto, params) {
    if (!params) return texto;
    return texto.replace(/\{(\w+)\}/g, (m, k) => (params[k] !== undefined ? String(params[k]) : m));
}

function textos(idioma) {
    const codigo = normalizarIdioma(idioma);
    const diccionario = TEXTOS[codigo];
    const t = (clave, params) => {
        // Si falta en el idioma elegido se cae al castellano. Nunca vacío: un cartel en blanco
        // es ilegible para todos, y el que lo sufre es el que menos puede deducir qué decía.
        const texto = diccionario[clave] !== undefined ? diccionario[clave] : TEXTOS[IDIOMA_POR_DEFECTO][clave];
        if (texto === undefined) return clave;
        return interpolar(texto, params);
    };
    t.idioma = codigo;
    return t;
}

module.exports = { IDIOMAS, IDIOMA_POR_DEFECTO, TEXTOS, textos, normalizarIdioma, idiomaDelNavegador };
